2013-03-25 16:18:35
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/commands.py", line 1643, in run
WindowsError: [Error 5] Access is denied
2013-07-05 10:45:44
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/commands.py", line 1036, in run
  File ".\os.py", line 157, in makedirs
WindowsError: [Error 183] Cannot create a file when that file already exists: u'C:\\wamp\\www\\renvale.com\\secure'
2013-08-02 11:45:31
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/threads.py", line 101, in handler
  File "./sftp/commands.py", line 264, in run
  File "./sftp/commands.py", line 403, in do_operation
  File "./sftp/file_transfer.py", line 25, in handler
  File "./sftp/ftp_transport.py", line 472, in get
NotFoundError: Folder not found
2013-09-02 14:12:58
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File "./sftp/commands.py", line 2966, in run
  File "./sftp/commands.py", line 134, in create_default_config
IOError: [Errno 2] No such file or directory: u'C:\\wamp\\www\\katrinaotterweddings.co.uk\\sftp-config.json'
2013-09-18 13:53:47
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/commands.py", line 1779, in run
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect
2014-05-01 16:21:52
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 525, in get
NotFoundError: Folder not found
